#-----------------
# Versions
#-----------------
[versions]
jdkVersion = "21"
kotlin-dsl = "5.1.2"

#-----------------
# Libraries
#-----------------
[libraries]

#-----------------
# Plugins
#-----------------
[plugins]
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl" }